name: spark
version: 0.0.1-dev
author: "Chrome Team <apps-dev@chromium.org>"
homepage: https://github.com/GoogleChrome/spark
description: A Chrome app based development environment.
dependencies:
  ace:
    git: https://github.com/rmsmith/ace.dart.git
  analyzer_experimental: any
  browser: any
  chrome: any
  compiler_unsupported: any
dev_dependencies:
  args: any
  grinder:
    git: https://github.com/devoncarew/grinder.dart.git
  unittest: any
