name: spark
version: 0.0.1-dev
author: "Chrome Team <apps-dev@chromium.org>"
homepage: https://github.com/GoogleChrome/spark
description: A Chrome app based development environment.
dependencies:
  ace: any
  analyzer_experimental: any
  browser: any
  chrome: any
  chrome_gen: '>=0.0.4'
  compiler_unsupported: any
  logging: any
  polymer: any
dev_dependencies:
  grinder: any
  unittest: any
