name: spark
version: 0.1.4-dev
author: Chrome Team <apps-dev@chromium.org>
description: A Chrome app based development environment.
homepage: https://github.com/GoogleChrome/spark
dependencies:
  ace: '>=0.0.8'
  bootjack: any
  analyzer: any
  browser: any
  chrome_gen: '>=0.2.2'
  crc32: 0.1.3
  crypto: any
  intl: any
  logging: any
  mime: any
  spark_widgets:
    path: ../widgets
  unittest: any
dev_dependencies:
  args: any
  grinder: any
